package code

const BINARY_ADD = 23

const PRINT_ITEM = 71
const PRINT_NEWLINE = 72
const RETURN_VALUE = 83

const HAVE_ARGUMENT = 90

const LOAD_CONST = 100

const COMPARE_OP = 107
const JUMP_FORWARD = 110
const JUMP_ABSOLUTE = 113
const POP_JUMP_IF_FALSE = 114

const (
	COMPARE_LESS = iota
	COMPARE_LESS_EQUAL
	COMPARE_EQUAL
	COMPARE_NOT_EQUAL
	COMPARE_GREATER
	COMPARE_GREATER_EQUAL
)